export const UomDropdown = [
  { value: 'Parts per million(PPM)' },
  { value: 'Kilowatt-hour (kWh)' },
  { value: 'Centimeter (cm)' },
  { value: 'Square meter (Sqm)' },
  { value: 'Meter (m)' },
  { value: 'Square Kilometer (Sqkm)' },
  { value: 'Kilometer (km)' },
  { value: 'Millimeter (mm)' },
  { value: 'Feet (ft)' },
  { value: 'Square feet (sqft)' },
  { value: 'Inches (inch)' },
  { value: 'Mile' },
  { value: 'Square Yard' },
  { value: 'Yard' },
  { value: 'Running Meter (RM)' },
  { value: 'Milligram (mg)' },
  { value: 'Gram (g)' },
  { value: 'Kilogram (kg)' },
  { value: 'Ounce (oz)' },
  { value: 'Pound (lb)' },
  { value: 'Ton' },
  { value: 'Quintal' },
  { value: 'Millilitre (ml)' },
  { value: 'Litre (l)' },
  { value: 'Kilolitre (kl)' },
  { value: 'Cubic meter (Cum)' },
  { value: 'Cubic feet (cf)' },
  { value: 'Cubic Centimeter (cm3)' },
  { value: 'Fluid ounce (fl oz)' },
  { value: 'Gallon (gal)' },
  { value: 'Pint (pt)' },
  { value: 'Celsius (C)' },
  { value: 'Kelvin (K)' },
  { value: 'Fahrenheit (F)' },
  { value: 'Second (s)' },
  { value: 'Minute (min)' },
  { value: 'Hour (hr)' },
  { value: 'Day' },
  { value: 'Week' },
  { value: 'Month' },
  { value: 'Year' },
  { value: 'Litres per second (l/s)' },
  { value: 'Cubic feet per minute (cfm)' },
  { value: 'Liters per second (l/s)' },
  { value: 'Each' },
  { value: 'Lumsum' },
  { value: 'Number' },
  { value: 'Bag' },
  { value: 'Acre' },
  { value: 'Hectare' },
  { value: 'Guntha' },
  { value: 'Bigha' },
  { value: 'Biswa' },
  { value: 'Biswansi' },
  { value: 'Kaccha' },
  { value: 'Killa' },
  { value: 'Ghumaon' },
  { value: 'Kanal' },
  { value: 'Chatak' },
  { value: 'Dhur' },
  { value: 'Kattha' },
  { value: 'Ankanam' },
  { value: 'Cent' },
  { value: 'Kuncham' },
  { value: 'Furlong' },
  { value: 'Gaj' },
  { value: 'Hath' },
  { value: 'Inch' },
  { value: 'Newton' },
  { value: 'Hectometer' },
  { value: 'Decameter' },
  { value: 'Nanometer' },
  { value: 'Millimetre' },
  { value: 'Decimeter' },
  { value: 'Each' },
];
