export const SET_COMPANY = 'SET_COMPANY';
export const SET_ASSESSMENT_TYPE = 'SET_ASSESSMENT_TYPE';
export const SET_ASSESSMENT_COMPLETE = 'SET_ASSESSMENT_COMPLETE';
export const SET_NUMBER_OF_QUESTIONS = 'SET_NUMBER_OF_QUESTIONS';
export const SET_CLICKED_CARDS = 'SET_CLICKED_CARDS';
export const UPDATE_SELECTED_ROW_KEYS = 'UPDATE_SELECTED_ROW_KEYS';
export const SET_SELECTED_ROW_KEYS = 'SET_SELECTED_ROW_KEYS';
export const SET_SELECTED_EMISSIONTAB = 'SET_SELECTED_EMISSIONTAB';

// dropdown options
export const SET_STATIONARY_OPTIONS = 'SET_STATIONARY_OPTIONS';
export const SET_MOBILE_OPTIONS = 'SET_MOBILE_OPTIONS';
export const SET_PROCESS_OPTIONS = 'SET_PROCESS_OPTIONS';
export const SET_FUGITIVE_OPTIONS = 'SET_FUGITIVE_OPTIONS';
export const SET_ENERGY_CONSUMPTION_OPTIONS = 'SET_ENERGY_CONSUMPTION_OPTIONS';

// filters

export const SET_STATIONARY_FILTERS = 'SET_STATIONARY_FILTERS';

// emissions table data

export const SET_STATIONARY_TAB_DATA = 'SET_STATIONARY_TAB_DATA';

export const SCOPE_THREE_COLUMNS = 'SCOPE_THREE_COLUMNS';

export const SET_COUNTRIES_LIST = 'SET_COUNTRIES_LIST';
export const SET_FACILITY_SELECTED = 'SET_FACILITY_SELECTED';

export const SET_EXPANDED_ROW_KEYS = 'SET_EXPANDED_ROW_KEYS';

export const SET_PEER_EDIT_MODE = 'SET_PEER_EDIT_MODE';

export const SET_PEER_DATA_EDIT = 'SET_PEER_DATA_EDIT';

// Maturity Assessment

export const SET_MODAL_OPEN = 'SET_MODAL_OPEN';
export const SET__REPORT_MODAL_OPEN = 'SET__REPORT_MODAL_OPEN';
export const SET_MAX_DR = 'SET_MAX_DR';
export const SET_UNREAD_COUNT = 'SET_UNREAD_COUNT';
export const SET_NOTIFICATIONS_LIST = 'SET_NOTIFICATIONS_LIST';
export const SET_NOTIFICATION_TOGGLE = 'SET_NOTIFICATION_TOGGLE';

export const SET_ENTITY_INFO = 'SET_ENTITY_INFO';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';

export const SET_PREV_ACTIVE_TAB = 'SET_PREV_ACTIVE_TAB';
