import { combineReducers } from 'redux';
import {
  companyReducer,
  assessmentReducer,
  assessmentLevelReducer,
  numberOfQstnsReducer,
  selectionReducer,
  selectedRowKeysReducer,
  emissionTabReducer,
  stationaryOptionsReducer,
  mobileOptionsReducer,
  processOptionsReducer,
  fugitiveOptionsReducer,
  energyConsumptionReducer,
  stationaryFiltersReducer,
  emissionTabDataReducer,
  scopeThreeColumnsReducer,
  countriesListReducer,
  facilitySelectedReducer,
  expandedRowkeysReducer,
  peerEditModeReducer,
  peerEditDataReducer,
  MaturityAssessmentReducer,
  ReportComplianceReducer,
  maxDrReducer,
  unreadCountReducer,
  notificationListReducer,
  notificationToggleReducer,
  entityInfoReducer,
  currentPageReducer,
} from './Reducers';
import { setFugitiveOptions } from './Actions';

export const rootReducer = combineReducers({
  company: companyReducer,
  assessmentType: assessmentReducer,
  assessmentLevel: assessmentLevelReducer,
  numberOfQstns: numberOfQstnsReducer,
  rowSelection: selectionReducer,
  selectedRowKeys: selectedRowKeysReducer,
  emissionTab: emissionTabReducer,
  stationaryOptions: stationaryOptionsReducer,
  mobileOptions: mobileOptionsReducer,
  processOptions: processOptionsReducer,
  fugitiveOptions: fugitiveOptionsReducer,
  energyConsumptionOptions: energyConsumptionReducer,
  stationaryFilters: stationaryFiltersReducer,
  emissionTabData: emissionTabDataReducer,
  scopeThreeColumns: scopeThreeColumnsReducer,
  countriesList: countriesListReducer,
  facilitySelected: facilitySelectedReducer,
  expandedRowkeys: expandedRowkeysReducer,
  editMode: peerEditModeReducer,
  peereditData: peerEditDataReducer,
  maturityAssessmentModal: MaturityAssessmentReducer,
  ReportComplianceModal: ReportComplianceReducer,
  max_dr: maxDrReducer,
  unreadCount: unreadCountReducer,
  notificationList: notificationListReducer,
  notificationToggle: notificationToggleReducer,
  entityInfo: entityInfoReducer,
  currentPage: currentPageReducer,
});
