export const breadcrumbConfig = {
  '/environment/carbon-footprint': 'Environment / GHG Inventory',
  '/emission-calculator': 'Emission Calculator',
  '/process-emission': 'GHG Emission / Scope 1 / Form',
  '/environment/emissions': 'GHG Emission / Scope 1 ',
  '/emission/scope-two': 'GHG Emission / Scope 2 / Form',
  '/environment/scope2': 'GHG Emission / Scope 2 ',
  '/environment/carbon-footprint/details':
    'Emission from for the Reporting Period',
  '/environment/energy-consumption': 'Energy Consumption',
  '/environment/water-consumption': 'Water Consumption',
  '/environment/waste-generation': 'Waste Generation',
  '/social/employees': 'Employees',
  '/social/occupational-health': 'Occupational Health & Safety',
  '/social/development-training': 'Development & Training',
  '/social/performance-career': 'Performance & Career Development Reviews',
  '/social/incidents-discrimination': 'Incidents of Discrimination',
  '/social/impact-assessment': 'Social Impact Assessment',
  '/social/environmental-assessment': 'Environmental Impact Assessment',
  '/social/community-development': 'Community Development Programs',
  '/social/paternal-leave': 'Parental Leave',
  '/social/benefits': 'Benefits',
  '/governance/data-breach-incidents': 'Data Breach Incidents',
  '/governance/ethical-behavior': 'Ethical Behavior',
  '/governance/certification': 'Certifications',
  '/governance/sustainability-disclosures': 'Sustainability Disclosures',
  '/governance/assurance': 'Assurance',
  '/settings/name-of-the-facilities': 'Manage Facility Profiles',
  '/settings/onBoard-companies': 'Manage Company Profile',
  '/company-list': 'Company List',
  '/user-role': 'User Role Select',
  '/manage-client/create-profile': 'Company Profiles',
  '/super-admin-landing': 'Home',
  '/admin-landing': 'Home',
  '/landing-page': 'Home',
  '/notification-acceptance': 'Notification Acceptance',
  '/user-access-management/user-management': 'User Management / All Users',
  '/map-user-emission': 'User Mapping for Emission',
  '/role-mapping-emission':
    'User Role Mapping / ESG Metrics with GHG Calculation',
  '/map-user-compliance': 'User Role Mapping / Reporting Compliance / Form',
  '/user-mapping-emission':
    'User Role Mapping / ESG Metrics with GHG Calculation / Form',
  '/edit-role-mapping-emission-reviewer':
    'ESG Metrics with GHG Calculation Role Mapping / Reviewer / Edit',
  '/edit-role-mapping-emission-provider':
    'ESG Metrics with GHG Calculation Role Mapping / Provider / Edit',
  '/edit-role-mapping-emission-approver':
    'ESG Metrics with GHG Calculation Role Mapping / Approver / Edit',
  '/edit-user-compliance-reviewer':
    'Reporting Compliance Role Mapping / Reviewer / Edit',
  '/edit-user-compliance-provider':
    'Reporting Compliance Role Mapping / Provider / Edit',
  '/edit-user-compliance-approver':
    'Reporting Compliance Role Mapping / Approver / Edit',
  '/role-mapping-compliance': 'User Role Mapping / Reporting Compliance',
  '/user-access-management/user-role-mapping': 'User-Role Mapping',
  '/map-user': 'Map User',
  '/issb-gap-assesment': 'ISSB Gap Assessment',
  '/ISSB-Gap-Analysis-Results': 'ISSB Gap Analysis Results',
  '/business-partner': 'Business Partners',
  '/product-services': 'Product Services',
  '/add-partner': 'Add Partner',
  '/dashboard/details': 'Dashboard Details',
  '/governance/boardcomposition/dashboard':
    'Governance / Board and Management Dashboard',
  '/governance/compliance/dashboard': 'Governance / Compliance Dashboard',
  '/social/demographics/dashboard': 'Social / Employee Demographics Dashboard',
  '/social/safetyperformance/dashboard':
    'Social / Safety Performance Dashboard',
  '/target/environment-ghg': 'Environment / GHG Emission Targets',
  '/target/environment-water':
    'Environment / Water Consumption and Effluents Targets',
  '/target/environment-waste': 'Environment / Waste Generation Targets',
  '/target/governance': 'Governance / Governance Targets',
  '/target/social': 'Social / Social Targets',
  '/add-facility': 'Manage Facility Profiles / Form',
  '/add-facility/': 'Manage Facility Profiles / Form',
  '/add-entity': 'Add Entity',
  '/add-company': `Manage Company Profile / Edit`,
  '/product-services/form': 'Product Services Form',
  '/social/community-development/form': 'Community Development / Form',
  '/social/add-development-training/form': 'Development Training / Form',
  '/social/environmental-impact/form': 'Environmental Impact / Form',
  '/social/incidentof-discrimination/form': 'Incident of Discrimination / Form',
  '/social/occupational-health/form': 'Occupational Health / Form',
  '/social/add-parental-leaves/form': 'Parental Leave / Form',
  '/social/add-benefits/form': 'Benefits / Form',
  '/social/add-performance-career/form': 'Performance & Career / Form',
  '/social/add-impact-assessment/form': 'Social Impact Assessment / Form',
  '/social/employee/form': 'Employee / Form',
  '/governance/add-data-breach/form': 'Data Breach / Form',
  '/governance/add-ethical/form': 'Anti-Corruption Training / Form',
  '/governance/certification/form': 'Certification / Form',
  '/governance/sustainability/form': 'Sustainability / Form',
  '/governance/assurance/form': 'Assurance / Form',
  '/environment/energy-consumption/forms': 'Energy Consumption / Form',
  '/environment/water-consumption/forms': 'Water Consumption / Form',
  '/environment/waste-generation/forms': 'Waste Generation / Form',
  '/community/form': 'User Management / Form',
  '/business-partner/form': 'Business Partner / Form',
  // '/esg-config': 'ESG Configuration',
  // '/view-config': 'View ESG Configuration',
  '/view-currency-conversion': 'Currency Conversion',
  '/setting/reporting-boundary': 'Reporting Boundary',
  '/reporting-boundary/form': 'Reporting Boundary / Form',
  '/settings/esgReport-framework': 'ESG Reporting Framework',
  '/assesment': 'Start Assessment/ ESG Maturity Assessment',
  '/ISSB-Gap-Results': 'ISSB Gap Results / Enter Summarised Results',
  '/ISSB-Gap-Results-analysis': 'ISSB Gap Results / View Summarised Results',
  '/ISSBQuestionsPage':
    'ISSB Gap Assessment / Core Content / Metrics and Targets',
  '/ISSB-Gap-assesment/core-content': 'ISSB Gap Assessment / Core Content',
  '/ISSB-Gap-assesment/application-guidance':
    'ISSB Gap Assessment / Application Guidance',
  '/settings/company/onboarding-company': 'Onboarding Company',
  '/settings/supplier-list': 'Supplier List',
  '/settings/supplier-dashboard': 'Supplier Dashboard',
  '/settings/supplier/form': 'Supplier / Form',
  '/settings/disclosures-questionnaire': 'Disclosure Questionnaire',
  '/disclosure/assigned': 'Assigned Disclosure',
  '/disclosure/review': 'Disclosure Review',
  '/admin-dashboard': 'Admin Dashboard',
  '/reporting-compliance/questionnaire': 'GRI Standards',
  '/reporting-compliance/generate-pdf': 'Generate PDF Report',
  '/reporting-compliance/sign-off': 'Reporting Compliance Sign Off',
  '/reports/compliance': 'GRI Standards',
  '/assessment-start': 'Start Assessment',
  '/assessment': 'Assessment Questions',
  '/assessment-level': 'Assessment Level',
  '/assessment-report': 'ESG Maturity Assessment Report',
  '/assessment-end': 'Assessment Recommendations / Topics',
  '/assessment-subtopics': 'Assessment Recommendations / Topics / Sub Topics',
  '/maturity-questionnaire': 'Maturity Assessment Questionnaire',
  '/maturity-questionnaire-edit':
    'Maturity Assessment Questionnaire / Add Question',
  '/maturity-levelscore': 'Maturity Assessment Level Score',
  '/maturity-levelscore-edit': 'Maturity Assessment Level Score / Edit',
  '/scope3/category-1':
    'GHG Emission / Scope 3 / Category 1 / Purchased Goods & Services ',
  '/scope3/category-1/form':
    'GHG Emission / Scope 3 / Category 1 / Purchased Goods & Services / Form',
  '/scope3/category-1/questionairres':
    'GHG Emission / Scope 3 / Category 1 / Questionnaires',
  '/scope3/category-2': 'GHG Emission / Scope 3 / Category 2 / Capital Goods',
  '/scope3/category-2/form':
    'GHG Emission / Scope 3 / Category 2 / Capital Goods / Form',
  '/scope3/category-2/questionairres':
    'GHG Emission / Scope 3 / Category 2 / Questionnaires',
  '/scope3/category-3':
    'GHG Emission / Scope 3 / Category 3 / Fuel & Energy-related Activities',
  '/scope3/category-3/form':
    'GHG Emission / Scope 3 / Category 3 / Fuel & Energy-related Activities / Form',
  '/scope3/category-3/landing': 'GHG Emission / Scope 3 / Category 3 ',
  '/scope3/category-5':
    'GHG Emission / Scope 3 / Category 5 / Waste Generated in Operations',
  '/scope3/category-5/form':
    'GHG Emission / Scope 3 / Category 5 / Waste Generated in Operations / Form',
  '/scope3/category-5/questionairres':
    'GHG Emission / Scope 3 / Category 5 / Questionnaires',
  '/scope3/category-13':
    'GHG Emission / Scope 3 / Category 13 / Downstream Leased Assets',
  '/scope3/category-13/form':
    'GHG Emission / Scope 3 / Category 13 / Downstream Leased Assets / Form',
  '/scope3/category-13/questionairres':
    'GHG Emission / Scope 3 / Category 13 / Questionnaires',
  '/scope3/category-6': 'GHG Emission / Scope 3 / Category 6 / Business Travel',
  '/scope3/category-6/form':
    'GHG Emission / Scope 3 / Category 6 / Business Travel / Form ',
  '/scope3/category-6/questionairres':
    'GHG Emission / Scope 3 / Category 6 / Questionnaires',
  '/board-composition-form': 'Board and Management Composition / Form',
  '/board-composition': 'Board and Management Composition ',
  '/fatalities-injuries-form': 'Safety Performance / Form',
  '/fatalities-injuries': 'Safety Performance',
  '/employee-demographics': 'Employee Demographics',
  '/employeeForm': 'Employee Demographics / Form',
  '/environment/water-withdrawal-consumption':
    'Water / Water Withdrawal and Consumption',
  '/environment/water-withdrawal-consumption-form':
    'Water / Water Withdrawal and Consumption / Form',
  '/environment/waste-management': 'Waste Management',
  '/environment/waste-management-form': 'Waste Management / Form',
  '/environment/effluents': 'Water / Effluents',
  '/environment/effluents-form': 'Water / Effluents / Form',
  '/governance/Incidents': 'Governance Compliance',
  '/governance/Incidents-form': 'Governance Compliance / Form',
  '/wastemanagement/dashboard': 'Environment / Waste Management Dashboard',
  '/watermanagement/dashboard': 'Environment / Water and Effluents Dashboard',
  '/emissionFactor': 'Custom Emission Factors / Form',
  '/emissionFactor/edit': 'Custom Emission Factors / Edit',
  '/emissionFactorList': 'Custom Emission Factors',
  '/peer-benchmarking': 'Peer Benchmarking Manage ESG Metrics',
  '/peer-benchmarking-add': 'Peer Benchmarking Manage ESG Metrics / Add',
  '/manage-gri-questions-table': 'Manage GRI Disclosure Questions',
  '/manage-gri-questions-edit': 'Manage GRI Disclosure Questions / Edit',
  '/ESG-peer-data': 'Peer Data Management',
  '/ESG-peer-data-edit': 'Peer Data Management / Add',
  '/admin-bench': 'Benchmark Configuration',
  '/admin-bench-edit': 'Benchmark Configuration / Edit',
  '/admin-bench-view': 'Peer Data Overview',
  '/assessment-view-responses':
    'Maturity Assessment Questionnaires / View Responses',
  '/assessment-edit-responses':
    'Maturity Assessment Questionnaires / View Responses / Edit',
  '/reports/dashboard': 'Reports',
  '/admin-peer-selection': 'Financial Filters',
  '/audit/logs': 'Audit Logs',
  '/issb-role-mapping': 'User Role Mapping / ISSB',
  '/issb-role-mapping-form': 'User Role Mapping / ISSB / Form',
  '/issb-role-mapping-edit': 'User Role Mapping /  ISSB / Edit',
  '/view-config-table': 'ESG Configuration',
  '/esg-config': 'ESG Configuration / Add',
  '/esg-config-edit': 'ESG Configuration / Edit',
  '/view-config': 'ESG Configuration / View',
  '/super-view': 'Super View',
  '/about-us': 'About Us',
  '/edit-company': 'Company Profiles / Edit',
};

export const pathRoutes: { [key: string]: string } = {
  'Scope 1': '/environment/emissions',
  ISSB: '/issb-role-mapping',
  'Scope 2': '/environment/scope2',
  'Category 1': 'scope3/category-1',
  'Category 2': '/scope3/category-2',
  'Category 3': '/scope3/category-3',
  'Category 5': '/scope3/category-5',
  'Category 6': '/scope3/category-6',
  'Category 13': '/scope3/category-13',
  'Water Withdrawal and Consumption':
    '/environment/water-withdrawal-consumption',
  Effluents: '/environment/effluents',
  'ISSB Gap Assessment': '/issb-gap-assesment',
  'Waste Management': '/environment/waste-management',
  'GRI Standards': '/reporting-compliance/questionnaire',
  'Assessment Recommendations': '/assessment-end',
  'Start Assessment': '/assessment-start',
  'User Management': '/user-access-management/user-management',
  'Reporting Compliance': '/role-mapping-compliance',
  'Reporting Compliance / Form': '/map-user-compliance',
  'ESG Metrics with GHG Calculation': '/role-mapping-emission',
  'ESG Metrics with GHG Calculation / Form': '/map-user-emission',
  'Reporting Compliance Role Mapping': '/role-mapping-compliance',
  'Manage Facility Profiles': 'settings/name-of-the-facilities',
  'Custom Emission Factors': '/emissionFactorList',
  'Client Profiles': 'manage-client/create-profile',
  'Maturity Assessment Questionnaire': '/maturity-questionnaire',
  'Maturity Assessment Level Score': '/maturity-levelscore',
  'Safety Performance': 'fatalities-injuries',
  'Employee Demographics': 'employee-demographics',
  'Board and Management Composition': 'board-composition',
  'Governance Compliance': 'governance/Incidents',
  'Peer Benchmarking Manage ESG Metrics': '/peer-benchmarking',
  'ESG Peer Data': '/ESG-peer-data',
  'Benchmark Configuration': '/admin-bench',
  'Maturity Assessment Questionnaires': '/assessment-view-responses',
  'ESG Maturity Assessment': '/assessment-edit-responses',
  'Financial Metrics': '/admin-peer-selection',
  'Audit Logs': '/audit/logs',
  Reports: '/reports/dashboard',
  Water: '/environment/water-withdrawal-consumption',
  Topics: '/assessment-end',
  'View Responses': '/assessment-view-responses',
  'Manage Company Profile': '/settings/onBoard-companies',
  'Peer Data Management': 'ESG-peer-data',
  'ESG Configuration': '/view-config-table',
  'View ESG Configuration': '/view-config-table',
  'Company Profiles': '/manage-client/create-profile',
  'Emissions Role Mapping': '/role-mapping-emission',
  'ESG Metrics with GHG Calculation Role Mapping': '/role-mapping-emission',
  'Manage GRI Disclosure Questions': '/manage-gri-questions-table',
  'ISSB Gap Results': '/ISSB-Gap-Results-analysis',
};
